# .readthedocs.yaml
# Configuración mínima para proyectos de solo documentación (.rst)

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  # Ajusta si tus archivos están en otra carpeta (por ejemplo, docs/source/conf.py)
  configuration: docs/source/conf.py

# No hace falta instalar dependencias si solo usas Sphinx base
python:
  install:
    - requirements: docs/requirements.txt
